security:
    providers:
        chain_provider:
            chain:
                providers: [administrators, users]
        users:
            entity: { class: 'App\Entity\Users', property: username }

        administrators:
            entity: { class: 'App\Entity\Administrators', property: id }
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: chain_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
    encoders:
        App\Entity\Users:
            algorithm: bcrypt

    access_control:
        - { path: ^/profile, roles: ROLE_USERS }
        - { path: ^/history, roles: ROLE_USERS }
        - { path: ^/security, roles: ROLE_USERS }
