home:
    path: /
    controller: App\Controller\HomeController::index

user_profile:
    path: /profile
    controller: App\Controller\UserController::getProfile

user_history:
    path: /history
    controller: App\Controller\UserController::getHistory

user_security:
    path: /security
    controller: App\Controller\UserController::resetSecurityDetails

register_user:
    path: /register
    controller: App\Controller\RegisterController::register

generate_token:
    path: /token/generate
    controller: App\Controller\TokenController::generate

input_token:
    path: /token/input/{username}
    controller: App\Controller\TokenController::input

reset_with_token:
    path: /token/reset/{username}/{token}
    controller: App\Controller\TokenController::reset
